# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: token.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import permissionmessages_pb2 as permissionmessages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btoken.proto\x12\x05token\x1a\x18permissionmessages.proto\"\xe5\x01\n\x1f_GenerateDisposableTokenRequest\x12?\n\x07\x65xpires\x18\x01 \x01(\x0b\x32..token._GenerateDisposableTokenRequest.Expires\x12\x12\n\nauth_token\x18\x02 \x01(\t\x12\x35\n\x0bpermissions\x18\x03 \x01(\x0b\x32 .permission_messages.Permissions\x12\x10\n\x08token_id\x18\x04 \x01(\t\x1a$\n\x07\x45xpires\x12\x19\n\x11valid_for_seconds\x18\x01 \x01(\r\"Z\n _GenerateDisposableTokenResponse\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\x12\x10\n\x08\x65ndpoint\x18\x02 \x01(\t\x12\x13\n\x0bvalid_until\x18\x03 \x01(\x04\x32u\n\x05Token\x12l\n\x17GenerateDisposableToken\x12&.token._GenerateDisposableTokenRequest\x1a\'.token._GenerateDisposableTokenResponse\"\x00\x42`\n\rmomento.tokenP\x01Z0github.com/momentohq/client-sdk-go;client_sdk_go\xaa\x02\x1aMomento.Protos.TokenClientb\x06proto3')



__GENERATEDISPOSABLETOKENREQUEST = DESCRIPTOR.message_types_by_name['_GenerateDisposableTokenRequest']
__GENERATEDISPOSABLETOKENREQUEST_EXPIRES = __GENERATEDISPOSABLETOKENREQUEST.nested_types_by_name['Expires']
__GENERATEDISPOSABLETOKENRESPONSE = DESCRIPTOR.message_types_by_name['_GenerateDisposableTokenResponse']
_GenerateDisposableTokenRequest = _reflection.GeneratedProtocolMessageType('_GenerateDisposableTokenRequest', (_message.Message,), {

  'Expires' : _reflection.GeneratedProtocolMessageType('Expires', (_message.Message,), {
    'DESCRIPTOR' : __GENERATEDISPOSABLETOKENREQUEST_EXPIRES,
    '__module__' : 'token_pb2'
    # @@protoc_insertion_point(class_scope:token._GenerateDisposableTokenRequest.Expires)
    })
  ,
  'DESCRIPTOR' : __GENERATEDISPOSABLETOKENREQUEST,
  '__module__' : 'token_pb2'
  # @@protoc_insertion_point(class_scope:token._GenerateDisposableTokenRequest)
  })
_sym_db.RegisterMessage(_GenerateDisposableTokenRequest)
_sym_db.RegisterMessage(_GenerateDisposableTokenRequest.Expires)

_GenerateDisposableTokenResponse = _reflection.GeneratedProtocolMessageType('_GenerateDisposableTokenResponse', (_message.Message,), {
  'DESCRIPTOR' : __GENERATEDISPOSABLETOKENRESPONSE,
  '__module__' : 'token_pb2'
  # @@protoc_insertion_point(class_scope:token._GenerateDisposableTokenResponse)
  })
_sym_db.RegisterMessage(_GenerateDisposableTokenResponse)

_TOKEN = DESCRIPTOR.services_by_name['Token']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\rmomento.tokenP\001Z0github.com/momentohq/client-sdk-go;client_sdk_go\252\002\032Momento.Protos.TokenClient'
  __GENERATEDISPOSABLETOKENREQUEST._serialized_start=49
  __GENERATEDISPOSABLETOKENREQUEST._serialized_end=278
  __GENERATEDISPOSABLETOKENREQUEST_EXPIRES._serialized_start=242
  __GENERATEDISPOSABLETOKENREQUEST_EXPIRES._serialized_end=278
  __GENERATEDISPOSABLETOKENRESPONSE._serialized_start=280
  __GENERATEDISPOSABLETOKENRESPONSE._serialized_end=370
  _TOKEN._serialized_start=372
  _TOKEN._serialized_end=489
# @@protoc_insertion_point(module_scope)
